### ISSUE TITLE
Some players cannot load the Minecraft normally

### ISSUE THREAD

**Issue by bunSakurAing** [williewillus/Botania#128]
**\* ATTENTION: detected classes with unsupported format ***
**\* DO NOT SUBMIT THIS CRASH REPORT TO FORGE ***

Contact authors of the following mods: 
  Botania

WARNING: coremods are present:
  InputFix (中文输入-1.8.x-v2.jar)
  ThaumcraftLoader ([核心mod]神秘时代-1.8.9-5.1.6.jar)
  DLFMLCorePlugin (移动光源1.8.8.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 16-2-21 下午7:33
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: vazkii.botania.common.Botania
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:154)
Caused by: java.lang.ClassNotFoundException: vazkii.botania.common.Botania
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:65)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:468)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
    ... 15 more
Caused by: java.lang.UnsupportedClassVersionError: vazkii/botania/common/Botania : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 43 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 4x Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 138511192 bytes (132 MB) / 356110336 bytes (339 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1756 Optifine OptiFine_1.8.9_HD_U_H3 32 mods loaded, 32 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1756.jar) 
    UC  Forge{11.15.1.1756} [Minecraft Forge](forge-1.8.9-11.15.1.1756.jar) 
    UC  InputFix{1.8.x-v2} [InputFix](minecraft.jar) 
    UC  chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits]([核心mod]凿子-mc1.8.9-v1.8.11.jar) 
    UC  worldedit{6.1.1} [WorldEdit]([核心mod]创世神-mc1.8.9-6.1.1.jar) 
    UC  mantle{1.8.9-0.7.jenkins72} [Mantle]([核心mod]匠魂前置.jar) 
    UC  tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct]([核心mod]匠魂-1.8.9-2.0.2.jar) 
    UC  ArchitectureCraft{1.3.1} [ArchitectureCraft]([核心mod]建筑师工艺-1.3.1-mc1.8.9.jar) 
    UC  MoreFurnaces{1.5.0} [More Furnaces]([核心mod]更多炉子-1.5.0-MC1.8.9.jar) 
    UC  BiomesOPlenty{3.0.0} [Biomes O' Plenty]([核心mod]更多生物群系-1.8.9-3.0.0.1922-universal.jar) 
    UC  Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UC  Thaumcraft{5.1.6} [Thaumcraft]([核心mod]神秘时代-1.8.9-5.1.6.jar) 
    UE  Botania{r1.8-249} [Botania]([核心mod]植物魔法-248-MC1.8-0.6.1.jar) 
    UC  customnpcs{1.8.8_beta} [CustomNPCs]([核心mod]自定义NPC1.8.8_beta%2817dec15%29.jar) 
    UC  foodcraft{1.2.0} [FoodCraft]([核心mod]食物工艺-16.2.4-1.2.2-1.8.9.jar) 
    UC  JEI{2.28.0.160} [Just Enough Items](物品管理器JEI1.8.9-2.28.0.160.jar) 
    UC  JEIAddons{0.12.0.57} [Just Enough Items Addons](JEI神秘时代扩展_1.8.9-0.12.0.57.jar) 
    UC  journeymap{5.1.3b1} [JourneyMap](旅行者地图-1.8.8-5.1.3b1-unlimited.jar) 
    UC  DynamicLights{1.3.9} [Dynamic Lights](移动光源1.8.8.jar) 
    UC  DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module](移动光源1.8.8.jar) 
    UC  DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](移动光源1.8.8.jar) 
    UC  DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](移动光源1.8.8.jar) 
    UC  DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](移动光源1.8.8.jar) 
    UC  DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](移动光源1.8.8.jar) 
    UC  DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](移动光源1.8.8.jar) 
    UC  DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](移动光源1.8.8.jar) 
    UC  DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](移动光源1.8.8.jar) 
    UC  DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](移动光源1.8.8.jar) 
    UC  DurabilityShow{2.1.2} [Durability Show](耐久显示-1.8.9-2.1.2.jar) 
    UC  Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](血量显示 1.1-2.jar) 
    UC  MouseTweaks{2.6.0} [Mouse Tweaks](鼠标手势-2.6.0-mc1.8.9.jar) 
    Loaded coremods (and transformers): 
InputFix (中文输入-1.8.x-v2.jar)
  lain.mods.inputfix.InputFixTransformer
ThaumcraftLoader ([核心mod]神秘时代-1.8.9-5.1.6.jar)

DLFMLCorePlugin (移动光源1.8.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 730/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
OptiFine Version: OptiFine_1.8.9_HD_U_H3
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.4.0
OpenGlRenderer: GeForce GT 730/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

[19:33:36] [Client thread/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# E:\相对世界 [V1.3.1正式版].minecraft\crash-reports\crash-2016-02-21_19.33.35-client.txt

**Comment by yrsegal** [comment]
Update to Java 8, come back if the problem persists.

**Comment by williewillus** [comment]
update to java 8
