### ISSUE TITLE
daybloom prime crash

### ISSUE THREAD

**Issue by reinder-s** [williewillus/Botania#136]
i saw in the lexica that there are daybloom/nightshade prime's
so i messed around a bit and in the end used the entitydata command to change the subtilename of a daybloom to that it became a prime version
but when i placed it i crashed

here is the report
hope it helps!
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 26-2-16 18:09
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
    at vazkii.botania.common.block.subtile.generating.SubTileDaybloom.writeToPacketNBT(SubTileDaybloom.java:76)
    at vazkii.botania.api.subtile.SubTileEntity.writeToPacketNBTInternal(SubTileEntity.java:64)
    at vazkii.botania.common.block.tile.TileSpecialFlower.writeCustomNBT(TileSpecialFlower.java:116)
    at vazkii.botania.common.block.tile.TileMod.func_145844_m(TileMod.java:56)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:571)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:518)
    at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:64)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at vazkii.botania.common.block.subtile.generating.SubTileDaybloom.writeToPacketNBT(SubTileDaybloom.java:76)
    at vazkii.botania.api.subtile.SubTileEntity.writeToPacketNBTInternal(SubTileEntity.java:64)
    at vazkii.botania.common.block.tile.TileSpecialFlower.writeCustomNBT(TileSpecialFlower.java:116)
    at vazkii.botania.common.block.tile.TileMod.func_145844_m(TileMod.java:56)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:571)
    at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:518)
    at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:64)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
    Level name: Thaumcraft 5!
    All players: 1 total; [EntityPlayerMP['reinder'/1256, l='Thaumcraft 5!', x=212,70, y=64,00, z=-130,82]]
    Chunk stats: ServerChunkCache: 707 Drop: 0
    Level seed: 1740350617803193004
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: 228,00,64,00,148,00 - World: (228,64,148), Chunk: (at 4,4,4 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 7614239 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 552813168 bytes (527 MB) / 1886773248 bytes (1799 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1761 29 mods loaded, 29 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1761.jar) 
    UCHIJAAAA   Forge{11.15.1.1761} [Minecraft Forge](forge-1.8.9-11.15.1.1761.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   intangible{0.0.23} [Intangible](intangible-1.8.9-0.0.23.jar) 
    UCHIJAAAA   JEI{2.28.1.162} [Just Enough Items](jei_1.8.9-2.28.1.162.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-18} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-18.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft](Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-unofficial-0.6.2.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0-pre12} [BuildCraft](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0-pre12} [BC Transport](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0-pre12} [BC Energy](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0-pre12} [BC Factory](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre12} [BC Silicon](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre12} [BC Robotics](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0-pre12} [BC Builders](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.11.jar) 
    UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.7} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.7.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons](JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   jeresources{0.3.4} [Just Enough Resources](JustEnoughResources-1.8.9-0.3.4.jar) 
    UCHIJAAAA   mantle{1.8.9-0.8.2.jenkins95} [Mantle](Mantle-1.8.9-0.8.2.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   Psi{beta-18} [Psi](Psi-beta-18.jar) 
    UCHIJAAAA   RandomThings{3.6.4} [Random Things](RandomThings-MC1.8.9-3.6.4.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct](TConstruct-1.8.9-2.1.0.jar) 
    UCHIJAAAA   worldedit{6.1.1} [WorldEdit](worldedit-forge-mc1.8.9-6.1.1.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

```
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - chiselsandbitsIntegration (Enabled/Not Forced)
    - TinkerDebug (Enabled/Not Forced)

Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['reinder'/1256, l='Thaumcraft 5!', x=212,70, y=64,00, z=-130,82]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by TheWhiteWolves** [comment]
ye thats what happens when you randomly change things, the flower being a prime isn't just that its called prime, it has other stuff in the background that you just messed up on it.

**Comment by williewillus** [comment]
Yeah they're not meant to be obtained. I'll see if this is an actual bug though

**Comment by yrsegal** [comment]
this might be due to using /blockdata. That can mess up unprepared tileentities.

**Comment by williewillus** [comment]
yeah this is because you didn't set all the tags the primus needs to work properly, so it crashes (namely, the primePositionX/Y/Z tags). this is a non-issue.
