### ISSUE TITLE
Crash, probably an issue with a manapool unloading

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#163]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.1.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7-3-16 16:23
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.SpreaderVariant, values=[MANA, REDSTONE, ELVEN, GAIA]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at vazkii.botania.common.block.tile.mana.TileSpreader.isDreamwood(TileSpreader.java:449)
    at vazkii.botania.common.block.tile.mana.TileSpreader.getBurst(TileSpreader.java:476)
    at vazkii.botania.common.block.tile.mana.TileSpreader.checkForReceiver(TileSpreader.java:463)
    at vazkii.botania.common.block.tile.mana.TileSpreader.updateEntity(TileSpreader.java:209)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:69)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at vazkii.botania.common.block.tile.mana.TileSpreader.isDreamwood(TileSpreader.java:449)
    at vazkii.botania.common.block.tile.mana.TileSpreader.getBurst(TileSpreader.java:476)
    at vazkii.botania.common.block.tile.mana.TileSpreader.checkForReceiver(TileSpreader.java:463)
    at vazkii.botania.common.block.tile.mana.TileSpreader.updateEntity(TileSpreader.java:209)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:69)

-- Block entity being ticked --
Details:
    Name: botania:spreader // vazkii.botania.common.block.tile.mana.TileSpreader
    Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-3878,72,-3279), Chunk: (at 10,4,1 in -243,-205; contains blocks -3888,0,-3280 to -3873,255,-3265), Region: (-8,-7; contains chunks -256,-224 to -225,-193, blocks -4096,0,-3584 to -3585,255,-3073)
    Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Hyxaru'/201, l='MpServer', x=-3784,76, y=97,00, z=-3136,92]]
    Chunk stats: MultiplayerChunkCache: 262, 262
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -28,00,64,00,-192,00 - World: (-28,64,-192), Chunk: (at 4,4,0 in -2,-12; contains blocks -32,0,-192 to -17,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 491521 game time, 793484 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 70 total; [EntityZombie['Zombie'/256, l='MpServer', x=-3787,53, y=45,00, z=-3071,94], EntityBat['Bat'/257, l='MpServer', x=-3793,56, y=42,22, z=-3069,69], EntityZombie['Zombie'/258, l='MpServer', x=-3784,50, y=66,00, z=-3075,91], EntityZombie['Zombie'/259, l='MpServer', x=-3793,53, y=37,00, z=-3085,84], EntityPlayerSP['Hyxaru'/201, l='MpServer', x=-3784,76, y=97,00, z=-3136,92], EntitySpider['Spider'/262, l='MpServer', x=-3823,50, y=14,00, z=-3076,50], EntityZombie['Zombie'/263, l='MpServer', x=-3820,97, y=54,00, z=-3082,56], EntityCreeper['Creeper'/265, l='MpServer', x=-3830,50, y=38,00, z=-3086,50], EntityCreeper['Creeper'/266, l='MpServer', x=-3829,50, y=60,00, z=-3080,50], EntitySkeleton['Skeleton'/267, l='MpServer', x=-3791,59, y=28,00, z=-3070,28], EntityBat['Bat'/271, l='MpServer', x=-3842,50, y=41,88, z=-3196,19], EntityAuraNode['Aura Node'/287, l='MpServer', x=-3682,50, y=73,50, z=-3220,50], EntityItem['item.item.bone'/1712, l='MpServer', x=-3737,81, y=59,00, z=-3171,88], EntityAuraNode['Aura Node'/308, l='MpServer', x=-3666,50, y=70,50, z=-3176,50], EntityAuraNode['Aura Node'/323, l='MpServer', x=-3670,50, y=73,50, z=-3128,50], EntityAuraNode['Aura Node'/324, l='MpServer', x=-3665,50, y=63,50, z=-3058,50], EntityZombie['Zombie'/202, l='MpServer', x=-3787,50, y=24,00, z=-3148,50], EntityZombie['Zombie'/203, l='MpServer', x=-3776,44, y=21,00, z=-3146,56], EntityBat['Bat'/204, l='MpServer', x=-3783,56, y=30,66, z=-3142,22], EntityBat['Bat'/205, l='MpServer', x=-3788,50, y=26,10, z=-3137,63], EntityZombie['Zombie'/206, l='MpServer', x=-3773,34, y=69,00, z=-3149,94], EntityZombie['Zombie'/207, l='MpServer', x=-3779,00, y=28,00, z=-3131,47], EntityBat['Bat'/208, l='MpServer', x=-3781,59, y=31,10, z=-3133,81], EntityBat['Bat'/209, l='MpServer', x=-3779,47, y=26,56, z=-3136,06], EntityZombie['Zombie'/210, l='MpServer', x=-3793,13, y=30,00, z=-3139,53], EntityZombie['Zombie'/211, l='MpServer', x=-3786,03, y=51,00, z=-3129,59], EntityZombie['Zombie'/212, l='MpServer', x=-3788,03, y=51,00, z=-3124,59], EntitySkeleton['Skeleton'/213, l='MpServer', x=-3793,28, y=27,00, z=-3133,44], EntityBat['Bat'/214, l='MpServer', x=-3795,06, y=36,10, z=-3126,31], EntityCreeper['Creeper'/215, l='MpServer', x=-3807,06, y=58,00, z=-3132,44], EntityItem['item.item.string'/216, l='MpServer', x=-3797,06, y=61,00, z=-3166,28], EntityItem['item.item.bone'/217, l='MpServer', x=-3796,59, y=61,00, z=-3166,88], EntityItem['item.item.string'/218, l='MpServer', x=-3795,41, y=61,00, z=-3159,53], EntityCreeper['Creeper'/219, l='MpServer', x=-3767,00, y=27,00, z=-3155,69], EntityZombie['Zombie'/220, l='MpServer', x=-3767,50, y=23,00, z=-3167,50], EntityZombie['Zombie'/221, l='MpServer', x=-3773,50, y=29,00, z=-3156,50], EntitySpider['Spider'/222, l='MpServer', x=-3767,50, y=24,00, z=-3164,50], EntityCreeper['Creeper'/223, l='MpServer', x=-3773,38, y=51,00, z=-3133,00], EntityZombie['Zombie'/224, l='MpServer', x=-3808,72, y=24,00, z=-3146,38], EntitySkeleton['Skeleton'/225, l='MpServer', x=-3756,50, y=38,00, z=-3138,50], EntitySkeleton['Skeleton'/226, l='MpServer', x=-3790,50, y=63,00, z=-3118,50], EntitySkeleton['Skeleton'/227, l='MpServer', x=-3812,50, y=25,00, z=-3138,16], EntityCreeper['Creeper'/228, l='MpServer', x=-3823,97, y=57,00, z=-3135,50], EntityZombie['Zombie'/229, l='MpServer', x=-3814,25, y=63,00, z=-3164,72], EntityZombie['Zombie'/230, l='MpServer', x=-3815,56, y=63,00, z=-3164,03], EntityCreeper['Creeper'/231, l='MpServer', x=-3793,50, y=12,00, z=-3180,50], EntityCreeper['Creeper'/232, l='MpServer', x=-3792,50, y=12,00, z=-3180,50], EntityZombie['Zombie'/233, l='MpServer', x=-3794,50, y=14,00, z=-3173,50], EntitySkeleton['Skeleton'/234, l='MpServer', x=-3802,50, y=63,00, z=-3173,50], EntityCreeper['Creeper'/235, l='MpServer', x=-3775,50, y=18,00, z=-3168,50], EntityZombie['Zombie'/236, l='MpServer', x=-3764,59, y=62,00, z=-3171,06], EntitySkeleton['Skeleton'/237, l='MpServer', x=-3745,50, y=61,00, z=-3162,50], EntitySkeleton['Skeleton'/238, l='MpServer', x=-3759,50, y=60,00, z=-3167,50], EntityAuraNode['Aura Node'/239, l='MpServer', x=-3756,50, y=82,50, z=-3133,50], EntitySpider['Spider'/240, l='MpServer', x=-3758,31, y=42,09, z=-3120,97], EntityCreeper['Creeper'/241, l='MpServer', x=-3757,50, y=45,00, z=-3177,97], EntityItem['item.tile.mushroom9'/242, l='MpServer', x=-3793,88, y=29,00, z=-3092,88], EntityBat['Bat'/243, l='MpServer', x=-3794,19, y=32,88, z=-3093,53], EntityZombie['Zombie'/244, l='MpServer', x=-3831,03, y=57,00, z=-3131,59], EntityZombie['Zombie'/245, l='MpServer', x=-3838,50, y=52,00, z=-3126,50], EntityBat['Bat'/246, l='MpServer', x=-3837,53, y=44,09, z=-3166,75], EntitySkeleton['Skeleton'/247, l='MpServer', x=-3769,91, y=13,00, z=-3197,00], EntitySkeleton['Skeleton'/248, l='MpServer', x=-3769,00, y=13,00, z=-3197,72], EntitySpider['Spider'/249, l='MpServer', x=-3742,72, y=41,09, z=-3166,09], EntityZombie['Zombie'/250, l='MpServer', x=-3741,38, y=40,00, z=-3165,56], EntityBat['Bat'/251, l='MpServer', x=-3743,75, y=60,10, z=-3162,25], EntitySkeleton['Skeleton'/252, l='MpServer', x=-3742,53, y=39,00, z=-3175,09], EntitySkeleton['Skeleton'/253, l='MpServer', x=-3736,88, y=59,00, z=-3171,50], EntityItem['item.item.rottenFlesh'/254, l='MpServer', x=-3843,13, y=71,00, z=-3142,63], EntityAuraNode['Aura Node'/255, l='MpServer', x=-3779,50, y=85,50, z=-3206,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 346462088 bytes (330 MB) / 885547008 bytes (844 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 12, tcache: 117, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.2.1} [Thaumcraft](Thaumcraft-1.8.9-5.2.1.jar) 
    UCHIJAAAA   Botania{r1.8-250} [Botania](Botania.r1.8-unofficial-0.6.4.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.1.jar)

```
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
Launched Version: 1.8.9-forge1.8.9-11.15.1.1764
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: alternate_textures_futureazoo.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
```

**Comment by Hyxaru** [comment]
It is similair to the one posted before me. I however, don't even use optifine. Just thaumcraft 5.2.1 and botania 0.6.4.
