### ISSUE TITLE
Some crashes when approaching chunks with botania

### ISSUE THREAD

**Issue by actos** [williewillus/Botania#171]
I've been migrating my base to a new sky island and while flying back and forth I've gotten a few crashes that look to be botania related.  I'm guessing it's chunk load/unload related.

java.lang.NullPointerException: Ticking block entity
    at vazkii.botania.common.block.tile.mana.TilePool.recieveMana(TilePool.java:125)
http://pastebin.com/kjY4Jwmz 
http://pastebin.com/pVusb6eb

java.lang.NullPointerException: Ticking block entity
    at vazkii.botania.common.block.tile.mana.TilePool.isFull(TilePool.java:118)
http://pastebin.com/1ux9aW32
http://pastebin.com/uPFfzL3E

java.lang.NullPointerException: Ticking block entity
    at mcmultipart.capabilities.MultipartCapabilityHelper.hasCapability(MultipartCapabilityHelper.java:22)
    at mcmultipart.block.TileMultipart.hasCapability(TileMultipart.java:120)
    at vazkii.botania.common.core.helper.InventoryHelper2.getInventory(InventoryHelper2.java:28)
http://pastebin.com/kiiYGXeG

**Comment by williewillus** [comment]
the frist two I have tentative fixes for, the third i think is a mcmultipart bug, try updating it to the most recent

**Comment by actos** [comment]
Cool.  I was getting the first two while air dashing towards the area with the flugal tiara's special ability.
I'll grab that mcmultipart update (sorry, didn't realize I was behind again) and if I can get the the crash to pop up again I'll report it over there.

**Comment by codewarrior0** [comment]
> java.lang.NullPointerException: Ticking block entity
> at vazkii.botania.common.block.tile.mana.TilePool.isFull(TilePool.java:118)
> http://pastebin.com/1ux9aW32
> http://pastebin.com/uPFfzL3E

FWIW, I can confirm this one with v0.6.4.2. Whenever the next version is out I'll bug the server owner to update.

**Comment by codewarrior0** [comment]
I have also encountered the first crash several times, where the block receiving mana from the mana pool has been a Mana Spreader and several different functional flowers. I can reliably reproduce the crash by teleporting to an area (via Thaumic Infusion teleports) that has these kinds of setups, but merely logging in at that area does not crash.

**Comment by kingzane** [comment]
I have the same issue on my friends server  any time i go out of or into a chunk with mana spreaders and other flowers, I crash in the same way each time with a different  generation flower or functional flower as the root it seems, its rather frustrating  cant even play like this ive had like 40 crashes over the last 3 days 
 this time it was my exoflames before this crash it was the  agracarnations

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at vazkii.botania.common.block.tile.mana.TilePool.recieveMana(TilePool.java:125)
    at vazkii.botania.api.subtile.SubTileFunctional.onUpdate(SubTileFunctional.java:69)
    at vazkii.botania.common.block.subtile.functional.SubTileExoflame.onUpdate(SubTileExoflame.java:34)
    at vazkii.botania.common.block.tile.TileSpecialFlower.updateEntity(TileSpecialFlower.java:97)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:69)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by williewillus** [comment]
hang in there, new build within the next two days

**Comment by actos** [comment]
Haven't seen any of these crashes since the latest release, looks like it's fixed to me

**Comment by codewarrior0** [comment]
Same here.

**Comment by williewillus** [comment]
Thanks for the update, enjoy!
