### ISSUE TITLE
Crash on placing Master Corprea Spark

### ISSUE THREAD

**Issue by ruifung** [williewillus/Botania#173]
java.lang.NullPointerException: Unexpected error
    at vazkii.botania.common.item.ItemCorporeaSpark.func_180614_a(ItemCorporeaSpark.java:45)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:135)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:403)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1491)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by williewillus** [comment]
~~full log on pastebin, and version plox~~ nvm I got it

**Comment by ruifung** [comment]
That. was fast. XD.

**Comment by ruifung** [comment]
Also, is it intended for sparks to be only placed on inventories?

**Comment by williewillus** [comment]
yes
