### ISSUE TITLE
Breaking the elven mana spreader crashes the server

### ISSUE THREAD

**Issue by shortybsd** [williewillus/Botania#182]
Version: Botania.r1.8-unofficial-0.6.3

Time: 3/15/16 8:30 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.SpreaderVariant, values=[MANA, REDSTONE, ELVEN, GAIA]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at vazkii.botania.common.block.tile.mana.TileSpreader.isULTRA_SPREADER(TileSpreader.java:451)
    at vazkii.botania.common.block.tile.mana.TileSpreader.getMaxMana(TileSpreader.java:641)
    at vazkii.botania.common.block.tile.mana.TileSpreader.isFull(TileSpreader.java:151)
    at vazkii.botania.common.block.tile.mana.TileSpreader.tryShootBurst(TileSpreader.java:425)
    at vazkii.botania.common.block.tile.mana.TileSpreader.updateEntity(TileSpreader.java:249)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:70)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at vazkii.botania.common.block.tile.mana.TileSpreader.isULTRA_SPREADER(TileSpreader.java:451)
    at vazkii.botania.common.block.tile.mana.TileSpreader.getMaxMana(TileSpreader.java:641)
    at vazkii.botania.common.block.tile.mana.TileSpreader.isFull(TileSpreader.java:151)
    at vazkii.botania.common.block.tile.mana.TileSpreader.tryShootBurst(TileSpreader.java:425)
    at vazkii.botania.common.block.tile.mana.TileSpreader.updateEntity(TileSpreader.java:249)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:70)

-- Block entity being ticked --
Details:
    Name: botania:spreader // vazkii.botania.common.block.tile.mana.TileSpreader
    Block type: ID #582 (tile.spreader // vazkii.botania.common.block.mana.BlockSpreader)
    Block data value: 2 / 0x2 / 0b0010
    Block location: World: (-211,77,1208), Chunk: (at 13,4,8 in -14,75; contains blocks -224,0,1200 to -209,255,1215), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
    Actual block type: ID #582 (tile.spreader // vazkii.botania.common.block.mana.BlockSpreader)
    Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: LU
    All players: 3 total; [EntityPlayerMP['shortybsd'/63073, l='LU', x=1134.86, y=68.00, z=-308.51], EntityPlayerMP['Carsweq'/141044, l='LU', x=-215.97, y=77.00, z=1209.75], EntityPlayerMP['BrandiS'/205677, l='LU', x=1049.73, y=66.50, z=-225.73]]
    Chunk stats: ServerChunkCache: 1862 Drop: 0
    Level seed: -6521993720181176447
    Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: 627.00,69.00,768.00 - World: (627,69,768), Chunk: (at 3,4,0 in 39,48; contains blocks 624,0,768 to 639,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
    Level time: 25353560 game time, 31404179 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 132103 (now: false), thunder time: 40241 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

**Comment by williewillus** [comment]
update to build 299

**Comment by shortybsd** [comment]
done and have same issue
http://pastebin.com/qqAcYGse

**Comment by yrsegal** [comment]
`// This doesn't make any sense!`
well said, crashlogger.
