### ISSUE TITLE
Breaking the elven mana spreader crashes the server with version Botania-unofficial.r1.8-299

### ISSUE THREAD

**Issue by shortybsd** [williewillus/Botania#183]
Version: Botania-unofficial.r1.8-299

When breaking an elven mana spreader it crashes the server with the following:

http://pastebin.com/qqAcYGse

Error out of latest.log

[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.botania.api.state.enums.SpreaderVariant, values=[MANA, REDSTONE, ELVEN, GAIA]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137) ~[ama$a.class:?]
    at vazkii.botania.common.block.tile.mana.TileSpreader.isULTRA_SPREADER(TileSpreader.java:454) ~[TileSpreader.class:?]
    at vazkii.botania.common.block.tile.mana.TileSpreader.getMaxMana(TileSpreader.java:649) ~[TileSpreader.class:?]
    at vazkii.botania.common.block.tile.mana.TileSpreader.isFull(TileSpreader.java:154) ~[TileSpreader.class:?]
    at vazkii.botania.common.block.tile.mana.TileSpreader.tryShootBurst(TileSpreader.java:428) ~[TileSpreader.class:?]
    at vazkii.botania.common.block.tile.mana.TileSpreader.updateEntity(TileSpreader.java:252) ~[TileSpreader.class:?]
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:69) ~[TileMod.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1718) ~[adm.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545) ~[le.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]

**Comment by williewillus** [comment]
Breaking how, just digging it?
(I can't reproduce)

**Comment by shortybsd** [comment]
Pickaxe, axe, Botania tools or Vanilla tools.

**Comment by williewillus** [comment]
do you maybe have a modlist?

**Comment by shortybsd** [comment]
Here you go brother, this is my modpack Element Legendary United

ArchitectureCraft-1.3.1-mc1.8.9 
BaseMetals-1.7.3 
BiomesOPlenty-1.8.9-3.0.0.1927-universal 
BloodMagic-1.8.9-2.0.0-19 
Bookshelf-API-1.8.9-2.3.6 
Botania-unofficial.r1.8-299 
buildcraft-7.2.0 
CandyCraft-1.3.1 
Chisel-MC1.8.9-0.0.2.7 
chiselsandbits-mc1.8.9-v1.8.10 
CustomNpcs_1.8.9_beta(21feb16) 
EnderTanks-1.8.9-1.2.1 
enderutilities-1.8.9-0.5.0 
EnderZoo-1.8.9-1.1.3.35 
fastTravel-1.8.8-1.0.4-universal 
Harvest-1.8.9-1.0.0-2 
HydCraft-1.8.9-3.1.65-universal 
IGW-Mod-1.8.9-1.2.4-4-universal 
intangible-1.8.9-0.0.25 
InventoryTweaks-1.60-beta-30 
IronBackpacks-1.8.9-2.0.5 
ironchest-1.8.9-6.0.125.770 
jei_1.8.9-2.28.7.174 
journeymap-1.8.8-5.1.3-unlimited 
k4lib-1.8.9-1.0.16-universal 
LLOverlayReloaded-1.0.5-mc1.8.9 
Mantle-1.8.9-0.9.1 
mcjtylib-1.8.9-1.8.1beta6 
MCMultiPart-1.0.7-universal 
MrCrayfishFurntiureModv3.6.1(1.8.9) 
NeoTech-1.8.9-2.4.1 
NetherEssence-4.0.1.1 
OpenComputers-MC1.8.9-1.6.0.17-dev 
OpenGrave-1.8.9-2.0 
plantmegapack-1.8.9.17 
PowerAdvantage-1.5.0 
ProgressiveAutomation-1.8.9-1.6.35 
RandomThings-MC1.8.9-3.6.6 
redstonepaste-mc1.8.8-1.7.2 
rftools-1.8.9-4.22beta25 
RoguelikeDungeons-1.8.9-1.4.5 
ShadowMC-1.8.9-3.0.0-SNAPSHOT 
ShetiPhianCore-1.8.9-3.1.0 
simplefluidtanks-1.8.9-1.3.0.2 
sodacanutils-2.0.4 
SteamAdvantage-1.5.1 
storagesilo-1.8.9-1.2.2b 
TConstruct-1.8.9-2.2.0b 
Thaumcraft-1.8.9-5.2.4 
Waila-1.6.0-B3_1.8.8

**Comment by TheWhiteWolves** [comment]
any chance you can narrow that down to either just the latest botania or botania + mod causing problem interaction

**Comment by williewillus** [comment]
also, does it happen in SP in your pack or just on a server
