### ISSUE TITLE
Force relays can cause CME's.

### ISSUE THREAD

**Issue by Laikulo** [williewillus/Botania#232]
Probably related to the new one world-per-thread model adopted in newer versions of MC,
A synchronized should deal with it.

Minecraft: 1.8.9
Forge 1855 (observed in others)

Stacktrace:

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at vazkii.botania.common.block.BlockPistonRelay.tickEnd(BlockPistonRelay.java:247)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_100_BlockPistonRelay_tickEnd_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
```

MC System Details:

```
Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1060968856 bytes (1011 MB) / 2373451776 bytes (2263 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024M -Xmx4096M -XX:MaxPermSize=256M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1808 41 mods loaded, 41 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808.jar) 
    UCHIJAAAA   Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   3DManeuverGear{1.7.10-@MAJOR@.@MINOR@.@REVIS@} [3D Maneuver Gear] (3DManeuverGear-1.8.9-0.6.jar) 
    UCHIJAAAA   basemetals{1.7.4} [Base Metals] (BaseMetals-1.7.4.jar) 
    UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAA   BetterFoliage{2.0.7} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.7.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0-refinery-test} [BuildCraft] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0-refinery-test} [BC Builders] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0-refinery-test} [BC Energy] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0-refinery-test} [BC Factory] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0-refinery-test} [BC Transport] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0-refinery-test} [BC Robotics] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0-refinery-test} [BC Silicon] (buildcraft-7.2.0-refinery-test.jar) 
    UCHIJAAAA   Chameleon{1.8.9-1.1.1} [Chameleon] (Chameleon-1.8.9-1.1.1.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAAAA   cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
    UCHIJAAAA   dsurround{2.0.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.5.6.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
    UCHIJAAAA   inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.12.180} [Just Enough Items] (jei_1.8.9-2.28.12.180.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
    UCHIJAAAA   malisiscore{1.8.9-2.0.5} [MalisisCore] (malisiscore-1.8.9-2.0.5.jar) 
    UCHIJAAAA   malisisdoors{1.8.9-3.1.3} [MalisisDoors] (malisisdoors-1.8.9-3.1.3.jar) 
    UCHIJAAAA   mantle{1.8.9-0.9.0.DEV.5d88f2d} [Mantle] (Mantle-1.8.9-0.9.0.DEV.5d88f2d.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   neoteric{0.0.2} [Neoteric] (Neoteric-0.0.2.jar) 
    UCHIJAAAA   packingtape{0.3.5} [Packing Tape] (Packing Tape-0.3.5.jar) 
    UCHIJAAAA   reforged{0.7-pre1} [Reforged] (reforged-0.7-pre1-alpha-1.8.9.jar) 
    UCHIJAAAA   xreliquary{1.8.9-1.3.1.261} [Reliquary] (Reliquary-1.8.9-1.3.1.261.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.6.2} [Storage Drawers] (StorageDrawers-1.8.9-2.6.2.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.2.1.DEV.8f3a4ed} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.DEV.8f3a4ed.jar) 
    UCHIJAAAA   tis3d{0.8.3.13} [TIS-3D] (TIS-3D-MC1.8.9-0.8.3.13.jar) 
    UCHIJAAAA   totemic{1.8.9-0.6.5} [Totemic] (Totemic-1.8.9-0.6.5.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

MalisisCorePlugin (malisiscore-1.8.9-2.0.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.7.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.6.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerDebug (Enabled/Not Forced)

    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['KJ4IPS'/8759, l='Creative', x=-701.97, y=56.00, z=1033.37]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by williewillus** [comment]
Worlds don't run in their own threads, but will investigate

**Comment by Laikulo** [comment]
Thanks, not sure where I got that in my head.
