### ISSUE TITLE
Nomming the Apple of Grisaia forces SERVER_STOPPED if you're still hungry when you finish eating in a dev env

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#242]
```
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:210) ~[NetworkSystem.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:802) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:683) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:155) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:532) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: bn
    at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:143) ~[forgeSrc-1.9-12.16.0.1852-1.9-PROJECT(NaturalPledge).jar:?]
    at vazkii.botania.common.item.relic.ItemInfiniteFruit.onUsingTick(ItemInfiniteFruit.java:64) ~[ItemInfiniteFruit.class:?]
    at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2694) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2079) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:252) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:339) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:174) ~[NetHandlerPlayServer.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:196) ~[NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307) ~[NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195) ~[NetworkSystem.class:?]
    ... 5 more
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: bn
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:90) ~[forgeSrc-1.9-12.16.0.1852-1.9-PROJECT(NaturalPledge).jar:?]
    at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:139) ~[forgeSrc-1.9-12.16.0.1852-1.9-PROJECT(NaturalPledge).jar:?]
    at vazkii.botania.common.item.relic.ItemInfiniteFruit.onUsingTick(ItemInfiniteFruit.java:64) ~[ItemInfiniteFruit.class:?]
    at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2694) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2079) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:252) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:339) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:174) ~[NetHandlerPlayServer.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:196) ~[NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307) ~[NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195) ~[NetworkSystem.class:?]
    ... 5 more
Caused by: java.lang.NoSuchFieldException: bn
    at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_66]
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:81) ~[forgeSrc-1.9-12.16.0.1852-1.9-PROJECT(NaturalPledge).jar:?]
    at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:139) ~[forgeSrc-1.9-12.16.0.1852-1.9-PROJECT(NaturalPledge).jar:?]
    at vazkii.botania.common.item.relic.ItemInfiniteFruit.onUsingTick(ItemInfiniteFruit.java:64) ~[ItemInfiniteFruit.class:?]
    at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2694) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2079) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:252) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:339) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:174) ~[NetHandlerPlayServer.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:196) ~[NetworkDispatcher$1.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307) ~[NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195) ~[NetworkSystem.class:?]
    ... 5 more
```

**Comment by yrsegal** [comment]
eeeeeedge cases!

**Comment by williewillus** [comment]
dafuq :P

**Comment by yrsegal** [comment]
10/10 best name for an issue
