### ISSUE TITLE
[Bug]Crash when try to place the altar beside a chest or furnace

### ISSUE THREAD

**Issue by q120248681** [williewillus/Botania#244]
The description in the log file

Description: Tesselating block model

java.lang.ClassCastException: net.minecraft.tileentity.TileEntityChest cannot be cast to vazkii.botania.common.block.tile.TileAltar
    at vazkii.botania.common.block.BlockAltar.getLightValue(BlockAltar.java:135)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:450)
    at net.minecraft.block.Block.func_185484_c(Block.java:352)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:329)
    at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_187491_a(BlockModelRenderer.java:594)
    at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:266)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:139)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:88)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:85)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:64)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:269)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:121)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:45)
    at java.lang.Thread.run(Unknown Source)

**Comment by williewillus** [comment]
#221
