### ISSUE TITLE
kek crash

### ISSUE THREAD

**Issue by folyfy** [williewillus/Botania#255]
java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=bites, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6]} to 7 on block minecraft:cake, it is not an allowed value

```
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:208)
at vazkii.botania.common.block.subtile.generating.SubTileKekimurus.onUpdate(SubTileKekimurus.java:47)
```

**Comment by yrsegal** [comment]
What version are you using?

**Comment by folyfy** [comment]
botania 302, forge 1865
