### ISSUE TITLE
Client crash when placing petals

### ISSUE THREAD

**Issue by ghost** [williewillus/Botania#284]
Forge: 19.-12.16.1.1901
Botania: 1.8-304

```
Time: 17.05.16 21:25
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at vazkii.botania.common.item.material.ItemPetal.func_180614_a(ItemPetal.java:35)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1512)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1743)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at vazkii.botania.common.item.material.ItemPetal.func_180614_a(ItemPetal.java:35)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1512)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
```

**Comment by yrsegal** [comment]
known, and fixed.

**Comment by ghost** [comment]
Ups, sry. Didn't see the issue.
