### ISSUE TITLE
Game crash using Petal Apothecare

### ISSUE THREAD

**Issue by benedikra** [williewillus/Botania#286]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 05-17-16 06:30 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at vazkii.botania.common.item.material.ItemPetal.func_180614_a(ItemPetal.java:35)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1512)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1743)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at vazkii.botania.common.item.material.ItemPetal.func_180614_a(ItemPetal.java:35)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1512)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['benedik777'/526, l='MpServer', x=-68.63, y=59.00, z=213.24]]
    Chunk stats: MultiplayerChunkCache: 81, 81
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-53,64,214), Chunk: (at 11,4,6 in -4,13; contains blocks -64,0,208 to -49,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 71374 game time, 71374 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 25 total; [EntitySpider['Araña'/256, l='MpServer', x=-31.70, y=71.00, z=175.30], EntityCreeper['Creeper'/257, l='MpServer', x=-24.51, y=62.00, z=202.84], EntityPig['Cerdo'/258, l='MpServer', x=-30.54, y=59.00, z=193.75], EntitySkeleton['Esqueleto'/259, l='MpServer', x=-23.50, y=67.00, z=231.50], EntityBat['Murciélago'/709, l='MpServer', x=-51.34, y=21.82, z=198.44], EntityCreeper['Creeper'/713, l='MpServer', x=-78.50, y=19.00, z=188.50], EntityPig['Cerdo'/213, l='MpServer', x=-58.50, y=67.00, z=169.23], EntityPig['Cerdo'/214, l='MpServer', x=-59.26, y=70.00, z=172.38], EntityPig['Cerdo'/215, l='MpServer', x=-53.58, y=71.00, z=165.50], EntityCreeper['Creeper'/216, l='MpServer', x=-51.50, y=71.00, z=167.50], EntityBat['Murciélago'/217, l='MpServer', x=-49.75, y=55.10, z=241.75], EntityPlayerSP['benedik777'/526, l='MpServer', x=-68.63, y=59.00, z=213.24], EntitySquid['Calamar'/611, l='MpServer', x=-103.60, y=56.00, z=218.85], EntityCreeper['Creeper'/612, l='MpServer', x=-25.50, y=15.00, z=177.50], EntitySquid['Calamar'/681, l='MpServer', x=-99.98, y=62.21, z=232.03], EntitySquid['Calamar'/622, l='MpServer', x=-103.60, y=60.00, z=204.33], EntityPig['Cerdo'/239, l='MpServer', x=-45.37, y=71.00, z=173.29], EntitySkeleton['Esqueleto'/240, l='MpServer', x=-39.51, y=69.00, z=186.31], EntitySquid['Calamar'/694, l='MpServer', x=-75.46, y=61.04, z=256.09], EntityBat['Murciélago'/696, l='MpServer', x=-104.50, y=46.10, z=253.75], EntityPig['Cerdo'/186, l='MpServer', x=-75.22, y=69.00, z=175.64], EntityPig['Cerdo'/187, l='MpServer', x=-66.23, y=70.00, z=173.53], EntityPig['Cerdo'/188, l='MpServer', x=-72.24, y=69.00, z=179.14], EntityPig['Cerdo'/189, l='MpServer', x=-73.26, y=67.00, z=189.28], EntitySkeleton['Esqueleto'/190, l='MpServer', x=-79.70, y=66.00, z=182.30]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:478)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Linux (amd64) version 4.4.0-22-generic
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 469012968 bytes (447 MB) / 974254080 bytes (929 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP 9.23 Powered by Forge 12.16.1.1907 Optifine OptiFine_1.9_HD_U_B2 13 mods loaded, 13 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1907.jar) 
    UCHIJAAAA   Forge{12.16.1.1907} [Minecraft Forge](forge-1.9-12.16.1.1907.jar) 
    UCHIJAAAA   bagginses{2.3.0b} [Bagginses](Bagginses-1.9-2.3.0b.jar) 
    UCHIJAAAA   Baubles{1.2.0.2} [Baubles](Baubles-1.9-1.2.0.2.jar) 
    UCHIJAAAA   bookshelf{1.2.0.226} [Bookshelf](Bookshelf-1.9-1.2.0.237.jar) 
    UCHIJAAAA   Botania{r1.8-304} [Botania](Botania-unofficial.r1.8-304.jar) 
    UCHIJAAAA   eplus{4.1.0.86} [Enchanting Plus](EnchantingPlus-1.9-4.1.0.97.jar) 
    UCHIJAAAA   endercrop{1.9-1.2-1836} [Ender Crop](endercrop-1.9.1.3.jar) 
    UCHIJAAAA   graves{1.9-b10-universal} [Graves Mod](graves-1.9-b10-universal.jar) 
    UCHIJAAAA   IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UCHIJAAAA   JEI{3.3.3.197} [Just Enough Items](jei_1.9-3.3.3.197.jar) 
    UCHIJAAAA   journeymap{1.9-5.2.0b1} [JourneyMap](journeymap-1.9-5.2.0b1-unlimited.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 11.2.0' Renderer: 'Mesa DRI Intel(R) Bay Trail '
    Launched Version: 1.9-forge1.9-12.16.1.1907
    LWJGL: 2.9.4
    OpenGL: Mesa DRI Intel(R) Bay Trail  GL version 3.0 Mesa 11.2.0, Intel Open Source Technology Center
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: Español (España)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Celeron(R) CPU N2840 @ 2.16GHz
OptiFine Version: OptiFine_1.9_HD_U_B2
Render Distance Chunks: 4
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 3.0 Mesa 11.2.0
OpenGlRenderer: Mesa DRI Intel(R) Bay Trail 
OpenGlVendor: Intel Open Source Technology Center
CpuCount: 2
```

**Comment by yrsegal** [comment]
Known and will be fixed in the next version.
