### ISSUE TITLE
[1.8.9] Crash with Mana Pump

### ISSUE THREAD

**Issue by Eufranio** [williewillus/Botania#292]
I had a crash when put a mana pump in a mana pool...

Description: Ticking block entity

```
java.lang.NullPointerException: Ticking block entity
    at vazkii.botania.common.block.tile.mana.TilePump.updateEntity(TilePump.java:87)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:69)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
```

@williewillus pls

**Comment by sameer** [comment]
Hi,
Is it possible to backport the fix for this from 1.9?

**Comment by williewillus** [comment]
No, sorry. 
You can set forge's config to "remove erroring tile entities" and it will erase the pump and let you load the world again

**Comment by sameer** [comment]
Thanks :)
