### ISSUE TITLE
CosmeticAttachRecipe creates stacks of null when combining botania cosmetics with non-botania base items

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#310]
IT'S BACK WILLIE D:

```
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1175) ~[EntityRenderer.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1138) ~[Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:404) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.client.renderer.RenderItem.renderItemOverlayIntoGUI(RenderItem.java:429) ~[RenderItem.class:?]
    at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:299) ~[GuiContainer.class:?]
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:114) ~[GuiContainer.class:?]
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:59) ~[InventoryEffectRenderer.class:?]
    at baubles.client.gui.GuiPlayerExpanded.drawScreen(GuiPlayerExpanded.java:83) ~[GuiPlayerExpanded.class:?]
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355) ~[ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1148) ~[EntityRenderer.class:?]
    ... 15 more
[11:14:43] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:646]: ---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/30/16 11:14 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.client.renderer.RenderItem.renderItemOverlayIntoGUI(RenderItem.java:429)
    at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:299)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:114)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:59)
    at baubles.client.gui.GuiPlayerExpanded.drawScreen(GuiPlayerExpanded.java:83)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1148)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1138)
    at net.minecraft.client.Minecraft.run(Minecraft.java:404)
    at net.minecraft.client.main.Main.main(Main.java:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
    at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.renderItemOverlayIntoGUI(RenderItem.java:429)
    at net.minecraft.client.gui.inventory.GuiContainer.drawSlot(GuiContainer.java:299)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:114)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:59)
    at baubles.client.gui.GuiPlayerExpanded.drawScreen(GuiPlayerExpanded.java:83)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)

-- Screen render details --
Details:
    Screen name: baubles.client.gui.GuiPlayerExpanded
    Mouse location: Scaled: (378, 181). Absolute: (757, 536)
    Screen size: Scaled: (720, 450). Absolute: (1440, 900). Scale factor of 2
```

**Comment by williewillus** [comment]
Did you find out what was happening?

**Comment by yrsegal** [comment]
i was using a read instead of write ._.

I am an idiot
