### ISSUE TITLE
Crashing when minecraft opens

### ISSUE THREAD

**Issue by nashbellow** [williewillus/Botania#313]
can't open any version of botania past 306
---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/30/16 3:57 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.ItemAxe.<init>(Lnet/minecraft/item/Item$ToolMaterial;FF)V
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemAxe.<init>(Lnet/minecraft/item/Item$ToolMaterial;FF)V
    at vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelAxe.<init>(ItemManasteelAxe.java:56)
    at vazkii.botania.common.item.equipment.tool.manasteel.ItemManasteelAxe.<init>(ItemManasteelAxe.java:52)
    at vazkii.botania.common.item.ModItems.init(ModItems.java:297)
    at vazkii.botania.common.core.proxy.CommonProxy.preInit(CommonProxy.java:107)
    at vazkii.botania.client.core.proxy.ClientProxy.preInit(ClientProxy.java:180)
    at vazkii.botania.common.Botania.preInit(Botania.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:584)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 183336136 bytes (174 MB) / 395005952 bytes (376 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1910 8 mods loaded, 8 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1910-1.9.4.jar) 
    UCH Forge{12.17.0.1910} [Minecraft Forge](forge-1.9.4-12.17.0.1910-1.9.4.jar) 
    UCH JEI{3.4.0.204} [Just Enough Items](jei_1.9.4-3.4.0.204.jar) 
    UCH BloodMagic{1.9.4-2.0.1-40} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.1-40.jar) 
    UCH Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCE Botania{r1.8-308} [Botania](Botania-unofficial.r1.8-308 %281%29.jar) 
    UCH soulshardstow{1.9.4-2.4.0-28} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.0-28.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 960/PCIe/SSE2'

**Comment by yrsegal** [comment]
update forge.

**Comment by williewillus** [comment]
^

**Comment by nashbellow** [comment]
Thanks
