### ISSUE TITLE
Adding piston crafting (and presumably any block with different placement directions) to an assembly/manufactory halo crashes the game on world loading.

### ISSUE THREAD

**Issue by lirannl** [williewillus/Botania#326]
From the log:

[19:00:39] [Client thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.client.event.RenderWorldLastEvent@6e5cccc8:
java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:piston, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:223) ~[are$a.class:?]
    at net.minecraft.block.BlockPistonBase.func_176203_a(BlockPistonBase.java:424) ~[aqu.class:?]
    at vazkii.botania.common.item.ItemCraftingHalo.render(ItemCraftingHalo.java:470) ~[ItemCraftingHalo.class:?]
    at vazkii.botania.common.item.ItemCraftingHalo.onRenderWorldLast(ItemCraftingHalo.java:404) ~[ItemCraftingHalo.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_ItemCraftingHalo_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:144) [ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1396) [bnd.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230) [bnd.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1039) [bnd.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077) [bcd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369) [bcd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:00:39] [Client thread/ERROR] [FML/]: Index: 4 Listeners:
[19:00:39] [Client thread/ERROR] [FML/]: 0: HIGHEST

**Comment by yrsegal** [comment]
This is fixed, but for next version.

**Comment by williewillus** [comment]
Fixed in next
