### ISSUE TITLE
Running inside a platform that's set to another block crashes

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#330]
```
net.minecraft.util.ReportedException: Exception while adding particle
    at net.minecraft.world.World.updateEntities(World.java:1894) ~[World.class:?]
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1885) ~[Minecraft.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:404) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.world.World.isOutsideBuildHeight(World.java:257) ~[World.class:?]
    at net.minecraft.world.World.getTileEntity(World.java:2557) ~[World.class:?]
    at vazkii.botania.client.core.handler.ColorHandler$4.colorMultiplier(ColorHandler.java:85) ~[ColorHandler$4.class:?]
    at net.minecraft.client.renderer.color.BlockColors.colorMultiplier(BlockColors.java:151) ~[BlockColors.class:?]
    at net.minecraft.client.particle.ParticleDigging.multiplyColor(ParticleDigging.java:67) ~[ParticleDigging.class:?]
    at net.minecraft.client.particle.ParticleDigging.init(ParticleDigging.java:60) ~[ParticleDigging.class:?]
    at net.minecraft.client.particle.ParticleDigging$Factory.getEntityFX(ParticleDigging.java:127) ~[ParticleDigging$Factory.class:?]
    at net.minecraft.client.particle.ParticleManager.spawnEffectParticle(ParticleManager.java:139) ~[ParticleManager.class:?]
    at net.minecraft.client.renderer.RenderGlobal.spawnEntityFX(RenderGlobal.java:2148) ~[RenderGlobal.class:?]
    at net.minecraft.client.renderer.RenderGlobal.spawnParticle(RenderGlobal.java:2102) ~[RenderGlobal.class:?]
    at net.minecraft.world.World.spawnParticle(World.java:1169) ~[World.class:?]
    at net.minecraft.world.World.spawnParticle(World.java:1156) ~[World.class:?]
    at net.minecraft.entity.Entity.createRunningParticles(Entity.java:1274) ~[Entity.class:?]
    at net.minecraft.entity.Entity.spawnRunningParticles(Entity.java:1260) ~[Entity.class:?]
    at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:510) ~[Entity.class:?]
    at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:254) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.Entity.onUpdate(Entity.java:430) ~[Entity.class:?]
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2093) ~[EntityLivingBase.class:?]
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:253) ~[EntityPlayer.class:?]
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:201) ~[EntityPlayerSP.class:?]
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2095) ~[World.class:?]
    at net.minecraft.world.World.updateEntity(World.java:2061) ~[World.class:?]
    at net.minecraft.world.World.updateEntities(World.java:1881) ~[World.class:?]
    ... 16 more
```

**Comment by yrsegal** [comment]
This also ocurrs when you run on an Abstruse Platform.
