### ISSUE TITLE
CME when rendering lightning [309]

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#349]
```
[22:32:17] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.RenderWorldLastEvent@6e80212a:
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_66]
    at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_66]
    at vazkii.botania.client.core.handler.LightningHandler.onRenderWorldLast(LightningHandler.java:102) ~[LightningHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_LightningHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:144) [ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1449) [EntityRenderer.class:?]
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1283) [EntityRenderer.class:?]
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1092) [EntityRenderer.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1140) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:404) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
[22:32:17] [Client thread/ERROR]: Index: 4 Listeners:
[22:32:17] [Client thread/ERROR]: 0: NORMAL
[22:32:17] [Client thread/ERROR]: 1: ASM: vazkii.botania.common.item.ItemCraftingHalo@5f4c930d onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 2: ASM: shadowfox.botanicaladdons.common.items.travel.bauble.ItemToolbelt$Companion$EventHandler@7d852967 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 3: ASM: shadowfox.botanicaladdons.common.block.base.BlockModLeaves$Companion@2cd3cbf5 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 4: ASM: vazkii.botania.client.core.handler.LightningHandler@42d28509 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 5: ASM: vazkii.botania.client.core.handler.BoundTileRenderer@3813f53b onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 6: ASM: vazkii.botania.client.core.handler.SubTileRadiusRenderHandler@22db8c16 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 7: ASM: vazkii.botania.client.core.handler.MultiblockRenderHandler@6bb1f7fe onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:17] [Client thread/ERROR]: 8: ASM: vazkii.botania.client.render.world.SkyblockRenderEvents@50763f2c onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[22:32:18] [Client thread/FATAL]: Unreported exception thrown!
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_66]
    at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_66]
    at vazkii.botania.client.core.handler.LightningHandler.onRenderWorldLast(LightningHandler.java:102) ~[LightningHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_LightningHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:144) ~[ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1449) ~[EntityRenderer.class:?]
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1283) ~[EntityRenderer.class:?]
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1092) ~[EntityRenderer.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1140) ~[Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:404) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
[22:32:18] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:646]: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 6/16/16 10:32 PM
Description: Unexpected error

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at vazkii.botania.client.core.handler.LightningHandler.onRenderWorldLast(LightningHandler.java:102)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_LightningHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:144)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1449)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1283)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1092)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1140)
    at net.minecraft.client.Minecraft.run(Minecraft.java:404)
    at net.minecraft.client.main.Main.main(Main.java:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
    at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at vazkii.botania.client.core.handler.LightningHandler.onRenderWorldLast(LightningHandler.java:102)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_LightningHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:144)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1449)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1283)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['yrsegal'/32, l='MpServer', x=-177.42, y=65.41, z=393.13]]
    Chunk stats: MultiplayerChunkCache: 1089, 1089
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-147,64,359), Chunk: (at 13,4,7 in -10,22; contains blocks -160,0,352 to -145,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1422292 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 11 total; [EntityHorse['Skeleton Horse'/1, l='MpServer', x=-227.86, y=64.00, z=363.84], EntityPlayerSP['yrsegal'/32, l='MpServer', x=-177.42, y=65.41, z=393.13], EntityMinecartChest['Minecart with Chest'/2, l='MpServer', x=-200.50, y=40.06, z=471.49], EntityCorporeaSpark['Corporea Spark'/3, l='MpServer', x=-180.50, y=65.50, z=396.50], EntityCorporeaSpark['Corporea Spark'/4, l='MpServer', x=-180.50, y=65.50, z=394.50], EntityCorporeaSpark['Corporea Spark'/5, l='MpServer', x=-180.50, y=68.50, z=392.50], EntityItemFrame['entity.ItemFrame.name'/6, l='MpServer', x=-179.97, y=67.50, z=392.50], EntityItemFrame['entity.ItemFrame.name'/7, l='MpServer', x=-179.97, y=64.50, z=392.50], EntityItemFrame['entity.ItemFrame.name'/8, l='MpServer', x=-179.97, y=64.50, z=393.50], EntityItemFrame['entity.ItemFrame.name'/9, l='MpServer', x=-154.03, y=65.50, z=383.50], EntityItemFrame['entity.ItemFrame.name'/10, l='MpServer', x=-153.50, y=65.50, z=382.97]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
    at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2770)
    at net.minecraft.client.Minecraft.run(Minecraft.java:433)
    at net.minecraft.client.main.Main.main(Main.java:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
    at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Mac OS X (x86_64) version 10.10.5
    Java Version: 1.8.0_66, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 213603504 bytes (203 MB) / 1926234112 bytes (1837 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 0 total; 
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.28 Powered by Forge 12.17.0.1965 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.9.4-12.17.0.1965-PROJECT(NaturalPledge).jar) 
    UCHIJAAAA   Forge{12.17.0.1965} [Minecraft Forge] (forgeSrc-1.9.4-12.17.0.1965-PROJECT(NaturalPledge).jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   Botania{r1.8-309} [Botania] (Botania-unofficial.r1.8-309.jar) 
    UCHIJAAAA   botanicaladdons{GRADLE:VERSION.GRADLE:BUILD} [Natural Pledge] (NaturalPledge) 
    UCHIJAAAA   JEI{3.4.0.202} [Just Enough Items] (jei_1.9.4-3.4.0.202.jar) 
    Loaded coremods (and transformers): 
    Launched Version: 1.9.4
    LWJGL: 2.9.2
    OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-10.6.33, Intel Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: net.minecraft.client.Minecraft$15@2ffd16a9
```

**Comment by PlasmaPower** [comment]
I guess that's what happens when you replace a ConcurrentLinkedQueue with a List :P

Was 96bf87333be04f6a9a202f3346d8d671722e0eec ever tested?

**Comment by williewillus** [comment]
yes, it was, and worked for me

**Comment by williewillus** [comment]
and that queue should not be accessed from more than one thread so something is up with the code itself, not the data structure choice

**Comment by PlasmaPower** [comment]
Well it was probably a ConcurrentLinkedQueue previously for a reason right?

Does the crash occur consistently?

**Comment by williewillus** [comment]
This code was from CodeChickenCore so no idea

I cannot reproduce. Perfectly fine with 64 unstable cubes (framerate gets a bit slow but that's it)

**Comment by PlasmaPower** [comment]
@yrsegal Which MC version and set of mods did you replicate it with? Does it occur consistently?

**Comment by PlasmaPower** [comment]
Oops, I forgot that's in the crash log. Does it occur consistently?

**Comment by yrsegal** [comment]
no, inconsistent.

**Comment by yrsegal** [comment]
This is in a dev env running latest commit of http://github.com/yrsegal/NaturalPledge.

**Comment by yrsegal** [comment]
The bug was produced through the lightning caused by https://github.com/yrsegal/NaturalPledge/blob/master/src/main/java/shadowfox/botanicaladdons/common/items/sacred/ItemMjolnir.kt if that matters

**Comment by yrsegal** [comment]
and it only happens near other lightnings.

**Comment by PlasmaPower** [comment]
@yrsegal I'm not saying that it's a bug with your addon, but can you reproduce it without using the addon?

**Comment by yrsegal** [comment]
Also, the lightning that does happen is far less opaque than normal.

**Comment by yrsegal** [comment]
it may well be a bug in my addon, however it shouldn't be possible for it to happen. It only occurs when swinging mjolnir, and i'm way too tired to exhaustively test it.

**Comment by williewillus** [comment]
i'll rewrite it soon anyways, it's a mess copied from CCC

**Comment by yrsegal** [comment]
I figured it out, and I also know why it didn't happen when you tested it. I haven't moved my particles over to packets, you see.

Lightning particles will _sometimes_ cause this if fired on world.isRemote=false.

**Comment by williewillus** [comment]
welp

**Comment by yrsegal** [comment]
There still is the fact that lightning is a lot more transparent than it
used to be though

**Comment by williewillus** [comment]
Fixed already
