### ISSUE TITLE
Crash when using Assembly Halo.

### ISSUE THREAD

**Issue by JosEffigy** [williewillus/Botania#385]
I just set a bucket and a magma cream to easily craft slimeballs. for some reason it crashes on hovering over the recipe.

java.lang.NullPointerException: Unexpected error
    at net.minecraftforge.items.ItemHandlerHelper.giveItemToPlayer(ItemHandlerHelper.java:160)
    at net.minecraftforge.items.ItemHandlerHelper.giveItemToPlayer(ItemHandlerHelper.java:148)
    at vazkii.botania.common.item.ItemCraftingHalo.consumeFromInventory(ItemCraftingHalo.java:215)
    at vazkii.botania.common.item.ItemCraftingHalo.consumeRecipeIngredients(ItemCraftingHalo.java:197)
    at vazkii.botania.common.item.ItemCraftingHalo.canCraft(ItemCraftingHalo.java:176)
    at vazkii.botania.common.item.ItemCraftingHalo.renderRecipe(ItemCraftingHalo.java:590)
    at vazkii.botania.common.item.ItemCraftingHalo.renderHUD(ItemCraftingHalo.java:552)
    at vazkii.botania.client.core.handler.HUDHandler.onDrawScreenPost(HUDHandler.java:146)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_HUDHandler_onDrawScreenPost_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:878)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:204)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1368)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mindforger** [comment]
full crashlog on pastebin please
