### ISSUE TITLE
Crash when using a Wand of the Forest on a Crafty Crate from a dispenser.

### ISSUE THREAD

**Issue by Lashriel** [williewillus/Botania#395]
Basically exactly what I said - I had a cake-farm set up, with an automatic Wand of the Forest to pre-clear my Crafty Crate from any failed crafting operations before trying a new crafting operation.

However, upon testing the setup, I crashed with the following log (cut from the moment of the crash, but reproducible if needed):

```
[22:52:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception while ticking a block
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) ~[bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at vazkii.botania.common.block.tile.TileCraftCrate.onWanded(TileCraftCrate.java:190) ~[TileCraftCrate.class:?]
    at vazkii.botania.common.block.BlockOpenCrate.onUsedByWand(BlockOpenCrate.java:153) ~[BlockOpenCrate.class:?]
    at vazkii.botania.common.block.dispenser.BehaviourWand.func_82487_b(BehaviourWand.java:35) ~[BehaviourWand.class:?]
    at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:12) ~[cq.class:?]
    at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:121) ~[alh.class:?]
    at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:147) ~[alh.class:?]
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:742) ~[ls.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217) ~[ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
    ... 4 more
[22:52:29] [Server thread/ERROR]: This crash report has been saved to: /home/john/.local/share/multimc5/instances/1.10.2/minecraft/crash-reports/crash-2016-07-13_22.52.29-server.txt
[22:52:29] [Server thread/INFO]: Stopping server
[22:52:29] [Server thread/INFO]: Saving players
[22:52:29] [Server thread/INFO]: Saving worlds
[22:52:29] [Server thread/INFO]: Saving chunks for level 'Survival'/Overworld
[22:52:29] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-38.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/13/16 10:52 PM
Description: Exception while ticking a block

java.lang.NullPointerException: Exception while ticking a block
    at vazkii.botania.common.block.tile.TileCraftCrate.onWanded(TileCraftCrate.java:190)
    at vazkii.botania.common.block.BlockOpenCrate.onUsedByWand(BlockOpenCrate.java:153)
    at vazkii.botania.common.block.dispenser.BehaviourWand.func_82487_b(BehaviourWand.java:35)
    at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:12)
    at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:121)
    at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:742)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at vazkii.botania.common.block.tile.TileCraftCrate.onWanded(TileCraftCrate.java:190)
    at vazkii.botania.common.block.BlockOpenCrate.onUsedByWand(BlockOpenCrate.java:153)
    at vazkii.botania.common.block.dispenser.BehaviourWand.func_82487_b(BehaviourWand.java:35)
    at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:12)
    at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:121)
    at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:147)

-- Block being ticked --
Details:
    Block: minecraft:dispenser[facing=north,triggered=true]
    Block location: World: (198,112,572), Chunk: (at 6,7,12 in 12,35; contains blocks 192,0,560 to 207,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Stacktrace:
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:742)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)

-- Affected level --
Details:
    Level name: Survival
    All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/187, l='Survival', x=203.67, y=113.62, z=571.47]]
    Chunk stats: ServerChunkCache: 884 Drop: 0
    Level seed: 5339414252187781991
    Level generator: ID 06 - quark_realistic, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (132,64,256), Chunk: (at 4,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 352961 game time, 352961 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 5784 (now: false), thunder time: 119975 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 4.6.3-1-ARCH
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 253868616 bytes (242 MB) / 911212544 bytes (869 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -Xms512m -Xmx1024m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.0.2010 15 mods loaded, 15 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2010-universal.jar) 
    UCHIJAAAA   Forge{12.18.0.2010} [Minecraft Forge] (forge-1.10.2-12.18.0.2010-universal.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
    UCHIJAAAA   mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
    UCHIJAAAA   chiselsandbits{11.4} [Chisels & Bits] (chiselsandbits-11.4.jar) 
    UCHIJAAAA   Harvest{1.9.4-1.0.1-8} [Harvest] (Harvest-1.9.4-1.0.1-8.jar) 
    UCHIJAAAA   IronChest{7.0.4.792} [Iron Chest] (ironchest-1.10-7.0.4.792.jar) 
    UCHIJAAAA   JEI{3.7.3.223} [Just Enough Items] (jei_1.10.2-3.7.3.223.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
    UCHIJAAAA   RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
    UCHIJAAAA   MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
    UCHIJAAAA   Quark{beta-38} [Quark] (Quark-beta-38.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-38.jar)
  vazkii.quark.base.asm.ClassTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/187, l='Survival', x=203.67, y=113.62, z=571.47]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
[22:52:29] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# /home/john/.local/share/multimc5/instances/1.10.2/minecraft/crash-reports/crash-2016-07-13_22.52.29-server.txt
[22:52:29] [Client thread/INFO]: Waiting for the server to terminate/save.
[22:52:29] [Server thread/INFO]: Saving chunks for level 'Survival'/Nether
[22:52:29] [Server thread/INFO]: Saving chunks for level 'Survival'/The End
[22:52:29] [Server thread/INFO]: Mapping halted in /home/john/.local/share/multimc5/instances/1.10.2/minecraft/journeymap/data/sp/Survival/DIM0
[22:52:30] [Server thread/INFO]: Unloading dimension 0
[22:52:30] [Server thread/INFO]: Unloading dimension -1
[22:52:30] [Server thread/INFO]: Unloading dimension 1
[22:52:30] [Server thread/INFO]: Applying holder lookups
[22:52:30] [Server thread/INFO]: Holder lookups applied
[22:52:30] [Server thread/INFO]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[22:52:30] [Client thread/INFO]: Server terminated.
[22:52:30] [Client Shutdown Thread/INFO]: Stopping server
[22:52:30] [Client Shutdown Thread/INFO]: Saving players
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

```

This is on Minecraft 1.10.2, with Forge 1.10.2-12.18.1.2014 and the latest Botania. It does not happen when I manually empty the Crafty Crate, only when it happens from a Dispenser. This is also suggested by the crash log mentioning the dispenser a couple of times.

**Comment by vladfrangu** [comment]
First of all, pastebin.. It'll help.

Secondly I don't think that it was intended for that ti happen, but if its
a bug expect it to be checked / fixed / has already been fixed

**Comment by yrsegal** [comment]
onWanded takes a player, but then Botania uses that player's worldobj instead of the tile's own for the remote check. That's a problem since the dispenser isn't a player.

Suggested fix: replace player.worldObj.isRemote with worldObj.isRemote.
