### ISSUE TITLE
[1.10.2] [FTB Unstable] Pure Daisy turns into Runic Altar when the game is loaded

### ISSUE THREAD

**Issue by Daenyth** [williewillus/Botania#415]
I made a pure daisy in the normal way, and I place it in my world. When I save the game, shut it off, then load the world again, a runic altar is in that location. I'm not sure if it works since I haven't built up mana generation yet. When I break the altar, no item drops.

I also have this stack trace, from a glance at the code it looks like it's [here](https://github.com/williewillus/Botania/blob/master/src/main/java/vazkii/botania/common/block/mana/BlockRuneAltar.java#L95-L96) when I break the block

```
[19:24:23] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: vazkii.botania.common.block.tile.TileSpecialFlower cannot be cast to vazkii.botania.common.block.tile.TileSimpleInventory
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: vazkii.botania.common.block.tile.TileSpecialFlower cannot be cast to vazkii.botania.common.block.tile.TileSimpleInventory
    at vazkii.botania.common.block.mana.BlockRuneAltar.func_180663_b(BlockRuneAltar.java:96) ~[BlockRuneAltar.class:?]
    at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:565) ~[asv.class:?]
    at net.minecraft.world.World.func_180501_a(World.java:329) ~[aid.class:?]
    at net.minecraft.block.Block.removedByPlayer(Block.java:1106) ~[akf.class:?]
    at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:275) ~[lv.class:?]
    at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:333) ~[lv.class:?]
    at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) ~[lv.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) ~[me.class:?]
    at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[ja.class:?]
    at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[ja.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
    ... 5 more
```

**Comment by Daenyth** [comment]
It looks like Unstable has Botania 18-313, so I wonder if this is already fixed? The 314 release notes mention blocks changing when you place them, but the pure daisy works normally until I shut the game off.

**Comment by williewillus** [comment]
Yes, 314 fixes this.
