### ISSUE TITLE
Game crash involving player heads and Botania

### ISSUE THREAD

**Issue by DarkSerpent** [williewillus/Botania#444]
Hello! I recently tested this problem out on my Forge Server. Whenever a player places a head block down, this occurs:

```
[01:02:35] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering Block Entity
   at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:107) ~[bmk.class:?]
   at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92) ~[bmk.class:?]
   at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:772) ~[bma.class:?]
   at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1596) ~[blt.class:?]
   at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334) ~[blt.class:?]
   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
   at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_79]
   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
   at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-17.0.jar:?]
   at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[guava-17.0.jar:?]
   at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[guava-17.0.jar:?]
   at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[guava-17.0.jar:?]
   at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[guava-17.0.jar:?]
   at net.minecraft.client.resources.SkinManager.func_152788_a(SourceFile:125) ~[brj.class:?]
   at vazkii.botania.client.render.tile.RenderTileSkullOverride.render(RenderTileSkullOverride.java:49) ~[RenderTileSkullOverride.class:?]
   at vazkii.botania.client.render.tile.RenderTileSkullOverride.func_147500_a(RenderTileSkullOverride.java:38) ~[RenderTileSkullOverride.class:?]
   at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.func_147500_a(SourceFile:21) ~[bms.class:?]
   at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100) ~[bmk.class:?]
```

I believe this issue has to do with Botania, and I also believe I am using the latest Botania version supplied within the Curse page.

Thanks in advance!

**Comment by williewillus** [comment]
Minecraft and Botania version?

The class in question has not been used for a while in the 1.10 botania versions

**Comment by DarkSerpent** [comment]
Ah, I see.

The newest version of Botania on the Curse mod page is for 1.7.10, and the latest Botania version is r1.8. It appears I'm using an outdated version. I assume updating will fix the problem.

Do you think you could explain what's going on in the error though? I had assumed it was another mod causing problems with Botania.

**EDIT:** I almost forgot to thank you, so thanks! XD

**Comment by williewillus** [comment]
not sure, i'm not familiar with the skin rendering in 1.7 and it changed quite a bit in 1.8.
Anyhow, it's not something I have control over fixing (I only work on 1.10.2 currently), so sorry :/
