### ISSUE TITLE
Storage drawer/botania conflict ?

### ISSUE THREAD

**Issue by charchess** [williewillus/Botania#468]
Hello, 

am running several mods on a forge 1.10.2 12.18.1.2071 server including botania and storage drawer

I did crash when unlocking a storage drawer and soemthing tried to fill it

looking at log I had saw the message here-bottom and disabled botania...no more crash

Feel free to ask if you need anything else

Charchess

[09:32:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: 44
        at net.minecraft.item.Item$ToolMaterial.func_150995_f(Item.java:1581) ~[adx$a.class:?]
        at net.minecraft.item.Item$ToolMaterial.getRepairItemStack(Item.java:1604) ~[adx$a.class:?]
        at net.minecraft.item.ItemSword.func_82789_a(ItemSword.java:91) ~[afg.class:?]
        at vazkii.botania.common.crafting.recipe.RegenIvyRecipe.func_77569_a(RegenIvyRecipe.java:49) ~[RegenIvyRecipe.class:?]
        at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersComp.findAllMatchingRecipes(TileEntityDrawersComp.java:307) ~[TileEntityDrawersComp.class:?]
        at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersComp.findHigherTier(TileEntityDrawersComp.java:252) ~[TileEntityDrawersComp.class:?]
        at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersComp.populateSlots(TileEntityDrawersComp.java:182) ~[TileEntityDrawersComp.class:?]
        at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersComp.access$300(TileEntityDrawersComp.java:36) ~[TileEntityDrawersComp.class:?]
        at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersComp$CompCentralInventory.setStoredItem(TileEntityDrawersComp.java:527) ~[TileEntityDrawersComp$CompCentralInventory.class:?]
        at com.jaquadro.minecraft.storagedrawers.storage.CompDrawerData.setStoredItemRedir(CompDrawerData.java:40) ~[CompDrawerData.class:?]
        at com.jaquadro.minecraft.storagedrawers.inventory.DrawerItemHandler.insertItemInternal(DrawerItemHandler.java:126) ~[DrawerItemHandler.class:?]
        at com.jaquadro.minecraft.storagedrawers.inventory.DrawerItemHandler.insertItemFullScan(DrawerItemHandler.java:82) ~[DrawerItemHandler.class:?]
        at com.jaquadro.minecraft.storagedrawers.inventory.DrawerItemHandler.insertItem(DrawerItemHandler.java:71) ~[DrawerItemHandler.class:?]
        at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:40) ~[ItemHandlerHelper.class:?]
        at net.minecraftforge.items.ItemHandlerHelper.insertItemStacked(ItemHandlerHelper.java:106) ~[ItemHandlerHelper.class:?]
        at crazypants.enderio.capability.ItemTools.doInsertItem(ItemTools.java:129) ~[ItemTools.class:?]
        at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:253) ~[NetworkedInventory.class:?]
        at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:223) ~[NetworkedInventory.class:?]
        at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:174) ~[NetworkedInventory.class:?]
        at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:147) ~[NetworkedInventory.class:?]
        at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:103) ~[NetworkedInventory.class:?]
        at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:219) ~[ItemConduitNetwork.class:?]
        at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63) ~[ConduitNetworkTickHandler.class:?]
        at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47) ~[ConduitNetworkTickHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_250_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

**Comment by williewillus** [comment]
What were you inserting?

From my analysis this is a sword from a mod that has not set the repair material for their tool properly

**Comment by williewillus** [comment]
this is whoever that tool's mod author not setting their ToolMaterial's repairMaterial properly.
