### ISSUE TITLE
Crash with Flowers Getting Mana

### ISSUE THREAD

**Issue by dragsta** [williewillus/Botania#60]
I am playing on a F.T.B Unstable 1.8 server for reference  

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  thaumicinfusion (ThaumicInfusion-4.73.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/20/16 9:20 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at vazkii.botania.common.block.tile.mana.TilePool.recieveMana(TilePool.java:123)
    at vazkii.botania.api.subtile.SubTileFunctional.onUpdate(SubTileFunctional.java:69)
    at vazkii.botania.common.block.subtile.functional.SubTileAgricarnation.onUpdate(SubTileAgricarnation.java:34)
    at vazkii.botania.common.block.tile.TileSpecialFlower.updateEntity(TileSpecialFlower.java:98)
    at vazkii.botania.common.block.tile.TileMod.func_73660_a(TileMod.java:68)
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I have also had it say other flowers like the hopperhawk.

 Thank You

**Comment by williewillus** [comment]
Should be bandaided by 071bcef again, until I start the big refactor to fix the root cause of all of this

Let me know if this still happens in the next build
