### ISSUE TITLE
crash with Thaumcraft 5.1.4

### ISSUE THREAD

**Issue by XuyuEre** [williewillus/Botania#80]
crash with Thaumcraft 5.1.4
`<---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0+135.50d21.jar)
  DLFMLCorePlugin (DynamicLights-1.8.8.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-1.1.1.1BETA.jar)
  InputFix (InputFix-1.8.x-v2.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 16-1-26 下午7:54
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    vazkii/botania/common/block/BlockModFlower.func_176474_b(Lnet/minecraft/world/World;Ljava/util/Random;Lnet/minecraft/util/BlockPos;Lnet/minecraft/block/state/IBlockState;)V @10: aload_1
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2a2b 2d19 042c b801 4ab1 2b2d 1904 b200
    0x0000010: 68b9 0091 0200 c000 6a06 b801 4eb1     

```
at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)
```

Caused by: java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    vazkii/botania/common/block/BlockModFlower.func_176474_b(Lnet/minecraft/world/World;Ljava/util/Random;Lnet/minecraft/util/BlockPos;Lnet/minecraft/block/state/IBlockState;)V @10: aload_1
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2a2b 2d19 042c b801 4ab1 2b2d 1904 b200
    0x0000010: 68b9 0091 0200 c000 6a06 b801 4eb1     

```
at vazkii.botania.common.block.ModBlocks.init(ModBlocks.java:274)
at vazkii.botania.common.core.proxy.CommonProxy.preInit(CommonProxy.java:91)
at vazkii.botania.client.core.proxy.ClientProxy.preInit(ClientProxy.java:179)
at vazkii.botania.common.Botania.preInit(Botania.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
... 15 more
```
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 209595320 bytes (199 MB) / 443920384 bytes (423 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_H2 50 mods loaded, 50 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1722.jar) 
    UCH Forge{11.15.1.1722} [Minecraft Forge](forge-1.8.9-11.15.1.1722.jar) 
    UCH InputFix{1.8.x-v2} [InputFix](minecraft.jar) 
    UCH cei{0.1} [Chunk Edge Indicator]([区块查看]1.8.9-chunkedgeindicator-1.0.jar) 
    UCH gravestone{1.1.2} [Gravestone]([墓碑]Gravestone Mod 1.1.2.jar) 
    UCH tchelper{1.0} [TC Research-Helper]([神秘连接查询]tchelper-1.8.9-1.2.jar) 
    UCH candycraftmod{Beta 1.3.1} [CandyCraft]([糖果世界]CandyCraft-1.3.1%281.8.9%29-CN.jar) 
    UCH ActuallyAdditions{1.8.9-r24} [Actually Additions](ActuallyAdditions-1.8.9-r24.jar) 
    UCH AppleCore{1.3.0} [AppleCore](AppleCore-mc1.8.9-1.3.0+135.50d21.jar) 
    UCH Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCH aura{unspecified} [Aura Cascade](AuraCascade-1.8.8-v0.2.2a.jar) 
    UCH BetterThanBunnies{1.8.9-1.0.0} [BetterThanBunnies](BetterThanBunnies-1.8.9-1.0.0.jar) 
    UCH BloodMagic{1.8.9-2.0.0-9} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-9.jar) 
    UCE Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-0.5.2.2.jar) 
    UCH Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCH ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78—CN.jar) 
    UCH crafttweaker{3.0.0} [crafttweaker](CraftTweaker-Customized-1.8.8-3.0.1.jar) 
    UCH DynamicLights{1.3.9} [Dynamic Lights](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.8.8.jar) 
    UCH DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.8.8.jar) 
    UCH dsurround{1.1.1.1BETA} [Dynamic Surroundings](DynamicSurroundings-1.8.9-1.1.1.1BETA.jar) 
    UCH Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCH FTBL{2.0.2} [FTBLib](FTBLib-1.8.9-2.0.2.jar) 
    UCH FTBU{2.0.2} [FTBUtilities](FTBUtilities-1.8.9-2.0.2.jar) 
    UCH IGWMod{1.2.3-3} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.3-3-universal.jar) 
    UCH inventorytweaks{1.60-dev-28-3253249} [Inventory Tweaks](InventoryTweaks-1.60-dev-28.jar) 
    UCH IronChest{6.0.121.768} [Iron Chest](ironchest-1.8.9-6.0.121.768.jar) 
    UCH JEI{2.22.2.104} [Just Enough Items](jei_1.8.9-2.22.2.104.jar) 
    UCH Thaumcraft{5.1.4} [Thaumcraft](Thaumcraft-1.8.9-5.1.4.jar) 
    UCH JEIAddons{0.10.0.35} [Just Enough Items Addons](JEIAddons_1.8.9-0.10.0.35.jar) 
    UCH jeresources{0.3.0.@BUILD@} [Just Enough Resources](JustEnoughResources-1.8.9-0.3.0.jar) 
    UCH mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCH getalltheseeds{1.8.9a} [Pam's Get all the Seeds!](Pam's Get all the Seeds! 1.8.9a.jar) 
    UCH PneumaticCraft{1.13.4-5} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.4-5-universal.jar) 
    UCH RecipeTooltips{1.1.18} [RecipeTooltips](RecipeTooltips-1.8.9-1.1.18.jar) 
    UCH sem{1.4.3} [Steam Engines Mod](sem-mc1_8_9-1.4.3.jar) 
    UCH semmagie{1.4.3} [Steam Engines Mod - Magie Addon](sem-mc1_8_9-1.4.3.jar) 
    UCH StorageDrawers{1.8.9-2.2.1} [Storage Drawers](StorageDrawers-1.8.9-2.2.1.jar) 
    UCH tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCH WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.8.x-1.1.6.jar) 
    UCH wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    UCH XaeroMinimap{1.7.9} [Xaero's Minimap](xaeros_minimap_v1.7.9_Forge_1.8.9.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)

AppleCore (AppleCore-mc1.8.9-1.3.0+135.50d21.jar)
  squeek.applecore.asm.TransformerModuleHandler
DLFMLCorePlugin (DynamicLights-1.8.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
dsurroundcore (DynamicSurroundings-1.8.9-1.1.1.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
InputFix (InputFix-1.8.x-v2.jar)
  lain.mods.inputfix.InputFixTransformer
FMLPlugin (InventoryTweaks-1.60-dev-28.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4352' Renderer: 'Intel(R) HD Graphics 4600'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerDebug (Enabled/Not Forced)

> `

**Comment by williewillus** [comment]
Can you reproduce with just botania + thaumcraft?

**Comment by squeek502** [comment]
@gxy17886, update AppleCore and see if this error still happens: https://github.com/squeek502/AppleCore/releases/tag/v1.3.0

**Comment by XuyuEre** [comment]
The problem solved, I delete the useless MC files, delete the config file, update applecore, to solve this problem, I am sorry not to be able to feedback issues, please close the issues.

**Comment by yrsegal** [comment]
you can close the issue if you made it...
