### ISSUE TITLE
Floating Flowers and TiC Crash

### ISSUE THREAD

**Issue by Plurp13** [williewillus/Botania#93]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 2/2/16 2:03 PM
Description: Tesselating block in world

java.lang.ClassCastException: vazkii.botania.client.model.FloatingFlowerModel$CompositeBakedModel cannot be cast to net.minecraftforge.client.model.IFlexibleBakedModel
    at slimeknights.tconstruct.shared.tileentity.TileTable.getTableItem(TileTable.java:87)
    at slimeknights.tconstruct.tools.tileentity.TileCraftingStation.setInventoryDisplay(TileCraftingStation.java:44)
    at slimeknights.tconstruct.shared.tileentity.TileTable.writeExtendedBlockState(TileTable.java:65)
    at slimeknights.tconstruct.shared.block.BlockTable.getExtendedState(BlockTable.java:92)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:151)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:192)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:903)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at slimeknights.tconstruct.shared.tileentity.TileTable.getTableItem(TileTable.java:87)
    at slimeknights.tconstruct.tools.tileentity.TileCraftingStation.setInventoryDisplay(TileCraftingStation.java:44)
    at slimeknights.tconstruct.shared.tileentity.TileTable.writeExtendedBlockState(TileTable.java:65)
    at slimeknights.tconstruct.shared.block.BlockTable.getExtendedState(BlockTable.java:92)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175022_a(BlockRendererDispatcher.java:151)

-- Block being tesselated --
Details:
    Block type: ID #488 (tile.tconstruct.tooltables // slimeknights.tconstruct.tools.block.BlockToolTable)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (78,61,44), Chunk: (at 14,3,12 in 4,2; contains blocks 64,0,32 to 79,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:93)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:192)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:903)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Plurp13'/92, l='MpServer', x=76.30, y=61.00, z=42.40]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: 220.00,64.00,102.00 - World: (220,64,102), Chunk: (at 12,4,6 in 13,6; contains blocks 208,0,96 to 223,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1337807 game time, 1380746 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 94 total; [EntityBat['Bat'/2020894, l='MpServer', x=151.36, y=45.78, z=64.99], EntitySkeleton['Skeleton'/1995292, l='MpServer', x=45.38, y=43.00, z=56.84], EntityItem['item.item.dyePowder.black'/2002962, l='MpServer', x=81.22, y=32.00, z=-12.06], EntitySquid['Squid'/2024458, l='MpServer', x=28.81, y=62.42, z=52.97], EntitySquid['Squid'/2024459, l='MpServer', x=41.38, y=57.58, z=86.44], EntityZombie['Zombie'/2024966, l='MpServer', x=103.50, y=21.00, z=15.50], EntityAuraNode['Aura Node'/30, l='MpServer', x=128.50, y=63.50, z=4.50], EntityAuraNode['Aura Node'/34, l='MpServer', x=200.50, y=92.50, z=104.50], EntitySquid['Squid'/2024508, l='MpServer', x=86.51, y=58.98, z=77.34], EntitySquid['Squid'/2024509, l='MpServer', x=128.66, y=52.35, z=95.27], EntityItem['item.item.dyePowder.black'/2003504, l='MpServer', x=14.53, y=41.00, z=-10.06], EntitySquid['Squid'/2024495, l='MpServer', x=122.69, y=50.36, z=41.51], EntitySkeleton['Skeleton'/2019364, l='MpServer', x=153.50, y=36.00, z=65.50], EntityAuraNode['Aura Node'/1958946, l='MpServer', x=61.50, y=64.50, z=-13.50], EntityCreeper['Creeper'/2015830, l='MpServer', x=153.50, y=35.00, z=74.50], EntityZombie['Zombie'/2020947, l='MpServer', x=156.50, y=25.00, z=26.50], EntityItem['item.item.dyePowder.black'/2005070, l='MpServer', x=124.81, y=32.00, z=-12.09], EntityBat['Bat'/2024014, l='MpServer', x=102.40, y=17.06, z=82.65], EntitySkeleton['Grim Skeleton'/2022988, l='MpServer', x=147.56, y=41.00, z=119.06], EntityAuraNode['Aura Node'/1959496, l='MpServer', x=32.50, y=64.50, z=180.50], EntityAuraNode['Aura Node'/1959498, l='MpServer', x=47.50, y=64.50, z=2.50], EntityPlayerSP['Plurp13'/92, l='MpServer', x=76.30, y=61.00, z=42.40], EntityBat['Bat'/2020419, l='MpServer', x=150.30, y=26.03, z=74.59], EntityCreeper['Creeper'/1996925, l='MpServer', x=113.50, y=15.00, z=85.50], EntitySquid['Squid'/2024560, l='MpServer', x=20.89, y=55.81, z=101.76], EntitySquid['Squid'/2024547, l='MpServer', x=60.22, y=57.05, z=76.44], EntityZombie['Zombie'/2019468, l='MpServer', x=141.47, y=26.00, z=47.88], EntityZombie['Zombie'/2018952, l='MpServer', x=68.50, y=35.00, z=85.50], EntitySkeleton['Skeleton'/2023612, l='MpServer', x=94.41, y=39.00, z=82.91], EntityZombie['Zombie'/2008241, l='MpServer', x=144.50, y=29.00, z=53.50], EntityBat['Bat'/2023590, l='MpServer', x=148.42, y=23.62, z=43.43], EntityItem['item.item.dyePowder.black'/1996496, l='MpServer', x=109.13, y=46.00, z=67.13], EntitySquid['Squid'/2024656, l='MpServer', x=79.99, y=57.97, z=88.25], EntityDummy['entity.testdummy.Dummy.name'/1958596, l='MpServer', x=69.50, y=60.00, z=45.50], EntitySkeleton['Skeleton'/2021059, l='MpServer', x=134.50, y=14.00, z=31.50], EntitySquid['Squid'/2024702, l='MpServer', x=35.13, y=52.65, z=-1.55], EntitySquid['Squid'/2024703, l='MpServer', x=36.14, y=53.06, z=-1.66], EntitySquid['Squid'/2024700, l='MpServer', x=40.30, y=52.65, z=-2.34], EntitySquid['Squid'/2024701, l='MpServer', x=40.66, y=53.54, z=-7.95], EntitySquid['Squid'/2024698, l='MpServer', x=34.85, y=52.46, z=-4.78], EntitySquid['Squid'/2024699, l='MpServer', x=36.69, y=53.62, z=-4.75], EntitySquid['Squid'/2024697, l='MpServer', x=33.53, y=53.58, z=-0.24], EntityCreeper['Creeper'/2025204, l='MpServer', x=53.50, y=44.00, z=53.50], EntityBat['Bat'/2022636, l='MpServer', x=32.75, y=28.94, z=101.25], EntitySquid['Squid'/2024682, l='MpServer', x=45.47, y=61.49, z=81.56], EntitySkeleton['Skeleton'/2011929, l='MpServer', x=4.50, y=17.00, z=118.50], EntityZombie['Zombie'/2017557, l='MpServer', x=99.50, y=30.00, z=-25.50], EntityZombie['Zombie'/2017042, l='MpServer', x=115.50, y=22.00, z=12.50], EntityZombie['Zombie'/2013456, l='MpServer', x=156.09, y=25.00, z=27.63], EntitySkeleton['Skeleton'/2006286, l='MpServer', x=64.47, y=27.00, z=54.69], EntitySquid['Squid'/2024708, l='MpServer', x=32.40, y=54.00, z=-9.56], EntitySquid['Squid'/2024709, l='MpServer', x=100.24, y=59.48, z=31.98], EntitySquid['Squid'/2024706, l='MpServer', x=42.65, y=52.22, z=-4.54], EntitySquid['Squid'/2024707, l='MpServer', x=36.76, y=51.87, z=-7.21], EntitySquid['Squid'/2024704, l='MpServer', x=42.79, y=53.93, z=1.40], EntitySquid['Squid'/2024705, l='MpServer', x=36.84, y=53.69, z=-2.77], EntitySquid['Squid'/2024766, l='MpServer', x=24.50, y=56.03, z=36.62], EntityZombie['Zombie'/2013503, l='MpServer', x=100.50, y=27.00, z=-22.50], EntitySquid['Squid'/2024767, l='MpServer', x=107.05, y=56.36, z=90.18], EntityBat['Bat'/2008381, l='MpServer', x=35.31, y=32.58, z=75.58], EntitySquid['Squid'/2024765, l='MpServer', x=123.25, y=45.20, z=15.89], EntitySkeleton['Skeleton'/2022196, l='MpServer', x=146.16, y=29.00, z=25.50], EntityItem['item.item.dyePowder.black'/2004260, l='MpServer', x=93.81, y=34.00, z=-15.38], EntityZombie['Zombie'/2010915, l='MpServer', x=151.50, y=25.00, z=30.50], EntitySquid['Squid'/2024798, l='MpServer', x=50.89, y=46.27, z=-14.94], EntitySquid['Squid'/2024799, l='MpServer', x=52.27, y=45.00, z=-14.14], EntitySquid['Squid'/2024796, l='MpServer', x=47.08, y=45.11, z=-15.38], EntitySquid['Squid'/2024797, l='MpServer', x=48.18, y=44.85, z=-20.11], EntitySquid['Squid'/2024794, l='MpServer', x=13.44, y=52.91, z=61.79], EntitySquid['Squid'/2024795, l='MpServer', x=52.32, y=45.29, z=-12.88], EntityZombie['Zombie'/2024278, l='MpServer', x=42.50, y=32.00, z=88.50], EntityBat['Bat'/2016087, l='MpServer', x=8.64, y=15.46, z=97.47], EntityItem['item.item.dyePowder.black'/2009409, l='MpServer', x=136.09, y=35.00, z=5.69], EntitySquid['Squid'/2024820, l='MpServer', x=106.33, y=47.84, z=59.34], EntityZombie['Zombie'/2018671, l='MpServer', x=100.50, y=17.00, z=80.50], EntityAuraNode['Aura Node'/1961835, l='MpServer', x=-0.50, y=63.50, z=69.50], EntitySquid['Squid'/2024806, l='MpServer', x=55.34, y=45.26, z=-8.21], EntitySquid['Squid'/2024805, l='MpServer', x=51.89, y=46.42, z=-14.62], EntitySquid['Squid'/2024802, l='MpServer', x=56.63, y=46.46, z=-10.53], EntitySquid['Squid'/2024803, l='MpServer', x=53.65, y=45.38, z=-15.24], EntitySquid['Squid'/2024800, l='MpServer', x=55.70, y=45.87, z=-13.12], EntitySpider['Spider'/2023323, l='MpServer', x=142.50, y=24.00, z=44.50], EntitySkeleton['Skeleton'/2017176, l='MpServer', x=50.53, y=43.00, z=53.19], EntitySkeleton['Skeleton'/2023315, l='MpServer', x=143.50, y=29.00, z=24.50], EntitySkeleton['Skeleton'/2020230, l='MpServer', x=147.44, y=23.00, z=35.84], EntitySquid['Squid'/2024834, l='MpServer', x=101.69, y=59.51, z=103.72], EntityCreeper['Creeper'/2018179, l='MpServer', x=155.50, y=41.00, z=65.50], EntitySquid['Squid'/2024835, l='MpServer', x=124.01, y=53.62, z=3.78], EntityBat['Bat'/2023358, l='MpServer', x=71.72, y=34.20, z=79.41], EntityCreeper['Creeper'/2020791, l='MpServer', x=130.97, y=18.00, z=39.59], EntityZombie['Zombie'/2014637, l='MpServer', x=-1.50, y=18.00, z=114.88], EntityCreeper['Creeper'/2021343, l='MpServer', x=151.50, y=44.00, z=64.50], EntityBat['Bat'/2021323, l='MpServer', x=155.58, y=26.84, z=40.75], EntityZombie['Zombie'/2024420, l='MpServer', x=68.50, y=19.00, z=39.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Mac OS X (x86_64) version 10.11.3
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 146218056 bytes (139 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 104
    FML: MCP 9.19 Powered by Forge 11.15.0.1710 28 mods loaded, 28 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.0.1710.jar) 
    UCHIJAAAA   Forge{11.15.0.1710} [Minecraft Forge](forge-1.8.9-11.15.0.1710.jar) 
    UCHIJAAAA   bagginses{2.1.4} [Bagginses](Bagginses-1.8.9-2.1.4.jar) 
    UCHIJAAAA   BBG{3.0.0} [BetterBedrockGen](BBG-3.0.0.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1631-universal.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-6} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-6.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.1.4} [Thaumcraft](Thaumcraft-1.8.9-5.1.4.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-ebf399e.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.7.5} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.7.5.jar) 
    UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAAAA   IronChest{6.0.115.759} [Iron Chest](ironchest-1.8.9-6.0.115.759.jar) 
    UCHIJAAAA   JEI{2.16.2.78} [Just Enough Items](jei_1.8.9-2.16.2.78.jar) 
    UCHIJAAAA   JEIAddons{0.8.1.30} [Just Enough Items Addons](JEIAddons_1.8.9-0.8.1.30.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
    UCHIJAAAA   mantle{1.8.8-0.6.jenkins60} [Mantle](Mantle-1.8.8-0.6.jar) 
    UCHIJAAAA   mcmultipart{1.0.5} [MCMultiPart](MCMultiPart-1.0.5-universal.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   rftools{4.20beta11} [RFTools](rftools-1.8.9-4.20beta11.jar) 
    UCHIJAAAA   rftoolsdim{4.20beta13} [RFTools Dimensions](rftoolsdim-1.8.9-4.20beta13.jar) 
    UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAAAA   tconstruct{1.8.8-2.0.1} [Tinkers' Construct](TConstruct-1.8.8-2.0.1.jar) 
    UCHIJAAAA   VeinMiner{0.31.2_build.unknown} [Vein Miner](VeinMiner-1.8.9_0.31.2.unknown.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.31.2_build.unknown} [Mod Support](VeinMiner-1.8.9_0.31.2.unknown.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   denseores{1.0} [denseores](denseores-2.%28-1%29.0 %28alpha 1.8%29.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)

```
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerMaterials (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerDebug (Enabled/Not Forced)

Launched Version: 1.8.9-forge1.8.9-11.15.0.1710
LWJGL: 2.9.2
OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.8.14 310.42.15f01, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
```

**Comment by williewillus** [comment]
Can you give me steps to reproduce?

**Comment by Plurp13** [comment]
Aha sorry knew I was forgetting something. I crafted the floating flower in a TiC work station, I have no idea whether or not it's significant but it was hooked up to all the other Tinker's tables and chests, and immediately put the floating flower back into the table cuz I was gonna make a floating mana flower. It crashed before I could even get to the other flower to put it in and now I can't load up that world, it crashes as soon as I try.

**Comment by GirafiStudios** [comment]
You should probably try to update both Tinkers Construct and Botania. This probably got fixed since the versions you're using :)

**Comment by Plurp13** [comment]
Oh there've been updates? I should've known to check first >.<;

**Comment by Plurp13** [comment]
Um so I updated and now I'm getting a different crash, about redstring, before minecraft finishes loading up.

---- Minecraft Crash Report ----
// My bad.

Time: 2/5/16 5:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: vazkii/botania/client/render/tile/RenderTileRedString
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:205)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: vazkii/botania/client/render/tile/RenderTileRedString
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:64)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:540)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: vazkii.botania.client.render.tile.RenderTileRedString
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/animation/FastTESR
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.animation.FastTESR
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Mac OS X (x86_64) version 10.11.3
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 66446384 bytes (63 MB) / 281067520 bytes (268 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.0.1710 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.0.1710.jar) 
    UC  Forge{11.15.0.1710} [Minecraft Forge](forge-1.8.9-11.15.0.1710.jar) 
    UC  Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UE  Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-779cc76.jar) 
    Loaded coremods (and transformers):

**Comment by GirafiStudios** [comment]
Please use Pastebin or similiar to post the crashlog.
You might need to update Forge too.

**Comment by Plurp13** [comment]
Sorry, again >.<; I'll try that, now I just feel silly...

**Comment by Plurp13** [comment]
Uh, yeah, that fixed it....welp...sorry to have bothered you ^_^; thanks for the help, next time I'll try not being an idiot.
